### PR TITLE
This PR Improves Woocoommerce style

### PR DESCRIPTION
**Pull request by amjadr360**
This PR Improves Woocoommerce style.

| Before  | After |
| ------------- | ------------- |
|  image|  image  |
| image  | image  |
| image  | image  |
| image  | image  |
| image  | image  |
| image  | image  |
| image  | image  |

And more other small style tweaks

### CODE REVIEW

**Comment by clubkert** [comment]
Thanks, @amjadr360 . The only issue I see is with the button colors. The color + text color aren't very visible at times (and don't meet accessibility standards). I noticed this on the cart, checkout, shop, and product pages.

For example, here are the buttons on the cart page:
Screenshot 2023-01-06 at 2 21 15 PM


And here are the buttons from the home page:

Screenshot 2023-01-06 at 2 21 26 PM


Here's another example from the cart page:
Screenshot 2023-01-06 at 2 21 46 PM

**Comment by amjadr360** [comment]
Fixed color accessibility.

**Comment by amjadr360** [comment]
LGTM,

@clubkert Please let me know if there is anything else.

**Comment by clubkert** [comment]
The only thing I noticed is the light helper text is sometimes hard to read. This was an issue with the Brisbane, Cairo, and Piraeus style variations.

Screenshot 2023-01-18 at 5 25 58 PM
Screenshot 2023-01-18 at 5 25 46 PM
Screenshot 2023-01-18 at 5 26 28 PM

**Comment by clubkert** [comment]
These now look good to me. Thanks!

**Review by clubkert — APPROVED** [review]

**Pull request merged**
